name: check build for PR

on:
  pull_request:
    branches:
      - master
 
jobs:
  build-schemes:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Build unpacked
        run: ./build.sh base.distr-unpacked

      - name: Build packed
        run: ./build.sh base.distr-unpacked

      - name: Build allpacked
        run: ./build.sh base.distr-allpacked

      - name: Install colorer
        run: |
          sudo apt-get -y install libicu-dev libxerces-c-dev libspdlog-dev libfmt-dev zlib1g-dev libminizip-dev
          wget https://github.com/colorer/Colorer-library/releases/download/v1.2.1/colorer.x64.v1.2.1.tar.gz
          mkdir bin
          tar -xf colorer.x64.v1.2.1.tar.gz -C ./bin

      - name: Test schemes
        working-directory: hrc/test
        run: python3 runtest.py


        
